### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by laaser-mself** [maxchuquimia/quickdraw#1]
LOVE the app, BTW.  VERY useful, thank you!!

It would be great to have a tool to draw a STRAIGHT line ... perhaps just holding down shift while drawing a line will force a straight line versus a drawn line?

Simple but very useful app!

**Comment by maxchuquimia** [comment]
Thanks for the feedback @laaser-mself !

I liked the idea a lot - I've implemented it and it should be available on the App Store in a few days once it's undergone Apple's review 😊
