### ISSUE TITLE
Feature Request: Change Keyboard Shortcuts

### ISSUE THREAD

**Issue by D1no** [maxchuquimia/quickdraw#10]
Hey, not sure if you're still active on this but gladly payed the 0,99 💳  as it just helped me to quickly record some guide gifs in combo with [kap](https://github.com/wulkano/kap). The menu bar was mentioned already, but what would really help me is changing the keyboard shortcuts. `L` `A` `R` `H` make perfect semantic sense but to quickly use it would be nice to remap them (i.e. QWER). Also since us europeans have different keyboard / more keys. Thanks a lot!

**Comment by maxchuquimia** [comment]
Hi @D1no, cheers! Yup I'm here on occasion, resolved two issues last week 😉 

It seems the menu bar is becoming a popular request so I can see that changing in the future for sure. 
Might have to wait a bit in regards to character binding changes, lets see if anyone else is interested and I'll need to have a think about the experience of actually setting a binding as there's currently no "settings" screen in the app. I do really like the idea of them existing in a row next to eachother though, perhaps providing 6789 along with the existing keys could make sense as an easier solution?

Cheers!

**Comment by D1no** [comment]
For a first try at power users: A plist what ever inside the Package Contents folder would great first throw too 🤗 so its unblocked from UI land.
