### ISSUE TITLE
Feature request: undo and eraser

### ISSUE THREAD

**Issue by bgbg** [maxchuquimia/quickdraw#3]
This is an excellent app. I use it a lot. Can you please add undo and eraser feature to it?

Thanks

**Comment by bgbg** [comment]
heh, actually Undo is already there. Is it possible that I also missed the eraser?

**Comment by maxchuquimia** [comment]
Thanks for the feedback! There is currently no eraser, might have to look into doing that!

**Comment by lingdocs** [comment]
Yes I would love an eraser. This is a **fantastic** app, the only one I found in the App Store that actually works and I am a happy customer.  However, it does really affect by teaching flow to not have an eraser. Often I would like to go back and erase something I drew in the past, without erasing other things. Currently the only thing I can do is to go back and undo things but that means I have to erase everything in order. 😕

**Comment by maxchuquimia** [comment]
Cheers for the reminder 😅  - I have made the backspace key delete all lines below the mouse' current position. Submitted to Apple just now so keep an eye out for this feature in 1.3.0! 🎉
