### ISSUE TITLE
Feature to hide bottom buttons helper

### ISSUE THREAD

**Issue by ww7** [maxchuquimia/quickdraw#6]
Please add a shortcut for buttons helper hiding

**Comment by maxchuquimia** [comment]
In the most recent version of the app you can press the `?` key on your keyboard to hide and show the initial keyboard shortcut helper message - it will remember that it's been hidden on next launch. Does that work for you?

**Comment by ww7** [comment]
Sorry, I mean toolbar
[](https://i.imgur.com/BUz7k2I.png)

**Comment by badcat** [comment]
I'd like this feature too. Hiding the buttons, not the entire app.

**Comment by g0t4** [comment]
Yeah I don't want the buttons (lower left 12345 and LARC) to show when I record my screen. 

I love the idea of an app that's a "layer" that can be treated like an app and I can switch to the app behind if I want to adjust things

**Comment by g0t4** [comment]
Nice work overall!

**Comment by maxchuquimia** [comment]
Thanks everyone, please enjoy 5067f16adc78a54a59aaa06d1030bd3fdadf8737 and look out for a new version soon if you're an AppStore user!
