### ISSUE TITLE
Feature request: move shapes while space bar is pressed

### ISSUE THREAD

**Issue by Najki** [maxchuquimia/quickdraw#9]
It would be nice to be able to move shapes (at least rectangles and circles) if I haven't yet released the mouse button. Many apps resolve that by allowing user to press and hold the space bar (while still not letting go of the mouse button) and then we enter a mode where the shape can be moved anywhere on screen. When we release the space bar, the shape stays in place and we can continue to change its size going back to the draw mode (still holding the mouse button). 

I've seen this feature in a very old version of Adobe Photoshop many years ago (and new versions still support it). Many other graphic design related apps had borrowed this idea since then. Including some screenshot/annotation apps.

**Comment by maxchuquimia** [comment]
This is a really nice idea and shouldn't be too difficult to implement, I'll see if I have some time soon! Thanks!

**Comment by maxchuquimia** [comment]
Sorry about the delay 😅 - submitted to Apple just now so keep an eye out for this feature in 1.3.0! 🎉

**Comment by Najki** [comment]
Thanks a lot!
